CREATE TABLE IF NOT EXISTS `aut`.`users` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL DEFAULT '',
  `username` VARCHAR(63) NOT NULL DEFAULT '',
  `hashed` VARCHAR(255) NOT NULL DEFAULT '',
  `email` VARCHAR(127) NOT NULL DEFAULT '',
  `active` TINYINT(1) NOT NULL DEFAULT 0,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `user_name_uniq` (`username` ASC),
  UNIQUE INDEX `email_uniq` (`email` ASC),
  INDEX `active_idx` (`active` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;
